---
# roles/security/tasks/main.yml
- name: Installation des outils de sécurité
  apt:
    name:
      - fail2ban
      - ufw
      - auditd
      - rkhunter
      - chkrootkit
      - aide
      - unattended-upgrades
      - apt-listchanges
    state: present

- name: Configuration de fail2ban
  template:
    src: jail.local.j2
    dest: /etc/fail2ban/jail.local
    backup: yes
  notify: restart fail2ban

- name: Activation de fail2ban
  service:
    name: fail2ban
    state: started
    enabled: yes

- name: Reset UFW to defaults
  ufw:
    state: reset
  when: ufw_enabled

- name: Configuration UFW - Politique par défaut
  ufw:
    state: enabled
    policy: deny
    direction: incoming
  when: ufw_enabled

- name: UFW - Autoriser SSH
  ufw:
    rule: allow
    port: '22'
    proto: tcp
  when: ufw_enabled

- name: UFW - Autoriser HTTP
  ufw:
    rule: allow
    port: '80'
    proto: tcp
  when: ufw_enabled

- name: UFW - Autoriser HTTPS
  ufw:
    rule: allow
    port: '443'
    proto: tcp
  when: ufw_enabled

- name: UFW - Autoriser Zabbix server
  ufw:
    rule: allow
    port: '10051'
    proto: tcp
  when: ufw_enabled

- name: UFW - Autoriser Zabbix agent
  ufw:
    rule: allow
    port: '10050'
    proto: tcp
  when: ufw_enabled

- name: Configuration des mises à jour automatiques de sécurité
  template:
    src: 50unattended-upgrades.j2
    dest: /etc/apt/apt.conf.d/50unattended-upgrades
    backup: yes

- name: Activation des mises à jour automatiques
  template:
    src: 20auto-upgrades.j2
    dest: /etc/apt/apt.conf.d/20auto-upgrades

- name: Configuration d'auditd pour la conformité RGPD
  template:
    src: auditd.conf.j2
    dest: /etc/audit/auditd.conf
    backup: yes
  notify: restart auditd

- name: Configuration des règles d'audit
  template:
    src: audit.rules.j2
    dest: /etc/audit/rules.d/audit.rules
    backup: yes
  notify: restart auditd

- name: Activation d'auditd
  service:
    name: auditd
    state: started
    enabled: yes

- name: Sécurisation SSH
  template:
    src: sshd_config.j2
    dest: /etc/ssh/sshd_config
    backup: yes
    validate: /usr/sbin/sshd -t -f %s
  notify: restart ssh

- name: Configuration de la bannière de connexion RGPD
  template:
    src: issue.net.j2
    dest: /etc/issue.net
    backup: yes

- name: Désactivation des services inutiles
  service:
    name: "{{ item }}"
    state: stopped
    enabled: no
  loop:
    - rpcbind
    - nfs-common
  ignore_errors: yes

- name: Configuration des limites système
  template:
    src: limits.conf.j2
    dest: /etc/security/limits.conf
    backup: yes

- name: Configuration sysctl pour la sécurité
  template:
    src: 99-security.conf.j2
    dest: /etc/sysctl.d/99-security.conf
  notify: reload sysctl